### ISSUE TITLE
[BUG]: Makefile doesn't install the package

### ISSUE THREAD

**Issue by yurivict** [openqasm/openqasm#381]
### OpenQASM version:

3.0

### Python version:

3.9

### Operating system:

FreeBSD

### What is the current behavior?

'make install' only installs dependencies and not the project itself.

### Steps to reproduce the problem

make install

### What is the expected behavior?

n/a

**Comment by jwoehr** [comment]
You did grab the correct package  with pip this time, right?
Looks to me like the openqasm3 package works okay.
```
(qdev_env) $ pip install openqasm3
Collecting openqasm3
  Downloading openqasm3-0.0.1-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.1/114.1 KB 620.3 kB/s eta 0:00:00
Installing collected packages: openqasm3
Successfully installed openqasm3-0.0.1
(qdev_env) $ pip install openqasm3[all]
Requirement already satisfied: openqasm3[all] in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (0.0.1)
Collecting antlr4-python3-runtime==4.9.2
  Using cached antlr4-python3-runtime-4.9.2.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Collecting pytest>=6.0
  Using cached pytest-7.1.2-py3-none-any.whl (297 kB)
Requirement already satisfied: pyyaml in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from openqasm3[all]) (6.0)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: tomli>=1.0.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pytest>=6.0->openqasm3[all]) (2.0.1)
Requirement already satisfied: packaging in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pytest>=6.0->openqasm3[all]) (21.3)
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Requirement already satisfied: attrs>=19.2.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pytest>=6.0->openqasm3[all]) (21.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from packaging->pytest>=6.0->openqasm3[all]) (3.0.8)
Using legacy 'setup.py install' for antlr4-python3-runtime, since package 'wheel' is not installed.
Installing collected packages: iniconfig, antlr4-python3-runtime, py, pluggy, pytest
  Running setup.py install for antlr4-python3-runtime ... done
Successfully installed antlr4-python3-runtime-4.9.2 iniconfig-1.1.1 pluggy-1.0.0 py-1.11.0 pytest-7.1.2
(qdev_env) jwoehr@pop-os:~/work/Qiskit/DEV$ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openqasm3 import ast
>>> from openqasm3 import parser
>>> from openqasm3 import visitor
>>> 
```

**Comment by jwoehr** [comment]
I also forked, cloned, and installed from source:
```
(qdev_env) $ git clone git@github.com:jwoehr/openqasm.git
Cloning into 'openqasm'...
remote: Enumerating objects: 8369, done.
remote: Counting objects: 100% (2511/2511), done.
remote: Compressing objects: 100% (524/524), done.
remote: Total 8369 (delta 2152), reused 2162 (delta 1975), pack-reused 5858
Receiving objects: 100% (8369/8369), 11.43 MiB | 2.80 MiB/s, done.
Resolving deltas: 100% (5297/5297), done.
(qdev_env) $ cd openqasm/
(qdev_env) $ make install
pip install -r requirements.txt
Requirement already satisfied: Sphinx>=4.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: sphinxcontrib-bibtex in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.4.2)
Collecting openqasm_pygments~=0.1.0
  Downloading openqasm_pygments-0.1.1-py3-none-any.whl (18 kB)
Requirement already satisfied: pylint in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (2.13.7)
Requirement already satisfied: reno in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (3.5.0)
Requirement already satisfied: packaging in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (21.3)
Requirement already satisfied: sphinxcontrib-devhelp in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (1.1.5)
Requirement already satisfied: docutils<0.18,>=0.14 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (0.17.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (0.7.12)
Requirement already satisfied: sphinxcontrib-qthelp in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (1.0.3)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: babel>=1.3 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (2.10.1)
Requirement already satisfied: Jinja2>=2.3 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: requests>=2.5.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: sphinxcontrib-applehelp in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: snowballstemmer>=1.1 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: sphinxcontrib-jsmath in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: Pygments>=2.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (2.12.0)
Requirement already satisfied: imagesize in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Sphinx>=4.0->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: pybtex>=0.24 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from sphinxcontrib-bibtex->-r requirements.txt (line 2)) (0.24.0)
Requirement already satisfied: pybtex-docutils>=1.0.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from sphinxcontrib-bibtex->-r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: mccabe<0.8,>=0.6 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pylint->-r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: astroid<=2.12.0-dev0,>=2.11.3 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pylint->-r requirements.txt (line 4)) (2.11.3)
Requirement already satisfied: dill>=0.2 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pylint->-r requirements.txt (line 4)) (0.3.4)
Requirement already satisfied: tomli>=1.1.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pylint->-r requirements.txt (line 4)) (2.0.1)
Requirement already satisfied: isort<6,>=4.2.5 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pylint->-r requirements.txt (line 4)) (5.10.1)
Requirement already satisfied: platformdirs>=2.2.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pylint->-r requirements.txt (line 4)) (2.5.2)
Requirement already satisfied: pbr in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from reno->-r requirements.txt (line 5)) (5.8.1)
Requirement already satisfied: PyYAML>=5.3.1 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from reno->-r requirements.txt (line 5)) (6.0)
Requirement already satisfied: dulwich>=0.15.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from reno->-r requirements.txt (line 5)) (0.20.35)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from astroid<=2.12.0-dev0,>=2.11.3->pylint->-r requirements.txt (line 4)) (1.7.1)
Requirement already satisfied: setuptools>=20.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from astroid<=2.12.0-dev0,>=2.11.3->pylint->-r requirements.txt (line 4)) (59.6.0)
Requirement already satisfied: wrapt<2,>=1.11 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from astroid<=2.12.0-dev0,>=2.11.3->pylint->-r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: pytz>=2015.7 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from babel>=1.3->Sphinx>=4.0->-r requirements.txt (line 1)) (2022.1)
Requirement already satisfied: urllib3>=1.24.1 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from dulwich>=0.15.0->reno->-r requirements.txt (line 5)) (1.26.9)
Requirement already satisfied: certifi in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from dulwich>=0.15.0->reno->-r requirements.txt (line 5)) (2021.10.8)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from Jinja2>=2.3->Sphinx>=4.0->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from packaging->Sphinx>=4.0->-r requirements.txt (line 1)) (3.0.8)
Requirement already satisfied: latexcodec>=1.0.4 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pybtex>=0.24->sphinxcontrib-bibtex->-r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: six in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from pybtex>=0.24->sphinxcontrib-bibtex->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from requests>=2.5.0->Sphinx>=4.0->-r requirements.txt (line 1)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/jwoehr/work/Qiskit/qdev_env/lib/python3.10/site-packages (from requests>=2.5.0->Sphinx>=4.0->-r requirements.txt (line 1)) (3.3)
Installing collected packages: openqasm_pygments
Successfully installed openqasm_pygments-0.1.1
(qdev_env) jwoehr@pop-os:~/work/Qiskit/DEV/openqasm$ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openqasm3 import parser
>>> from openqasm3 import visitor
>>> from openqasm3 import ast
```

**Comment by jwoehr** [comment]
To install from source:
```
(qdev_env) $ cd openqasm/source/openqasm
(qdev_env) $ pip install -e .
Obtaining file:///home/jwoehr/work/Qiskit/DEV/openqasm/source/openqasm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: openqasm3
  Running setup.py develop for openqasm3
Successfully installed openqasm3-0.1.0
(qdev_env) $ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openqasm3 import ast
```
... etc. ...

**Comment by jwoehr** [comment]
Hmm, doesn't seem to build the parser correctly.
```
$ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openqasm3 import parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwoehr/work/Qiskit/DEV/openqasm/source/openqasm/openqasm3/parser.py", line 49, in <module>
    from .antlr.qasm3Lexer import qasm3Lexer
ModuleNotFoundError: No module named 'openqasm3.antlr.qasm3Lexer'

```

**Comment by jwoehr** [comment]
So the build should work with `pip install -e .`
And maybe the Makefile in the top directory should be updated.

**Comment by yurivict** [comment]
Now the failure looks like this:
```
cd /disk-samsung/freebsd-ports/lang/py-openqasm/work/openqasm-3.0-849-gba2a0d8/source/openqasm &&  /usr/bin/env XDG_DATA_HOME=/disk-samsung/freebsd-ports/lang/py-openqasm/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/lang/py-openqasm/work  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/lang/py-openqasm/work/.cache  HOME=/disk-samsung/freebsd-ports/lang/py-openqasm/work PATH=/disk-samsung/freebsd-ports/lang/py-openqasm/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/disk-samsung/freebsd-ports/lang/py-openqasm/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" pip-3.9 install -e . --isolated --root=/disk-samsung/freebsd-ports/lang/py-openqasm/work/stage --prefix=/usr/local --ignore-installed --no-deps
Obtaining file:///disk-samsung/freebsd-ports/lang/py-openqasm/work/openqasm-3.0-849-gba2a0d8/source/openqasm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: openqasm3
  Running setup.py develop for openqasm3
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [31 lines of output]
        running develop
        /tmp/pip-build-env-7n8ni26y/overlay/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /tmp/pip-build-env-7n8ni26y/overlay/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        error: can't create or remove files in install directory
        
        The following error occurred while trying to add or remove files in the
        installation directory:
        
            [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/test-easy-install-11642.write-test'
        
        The installation directory you specified (via --install-dir, --prefix, or
        the distutils default setting) was:
        
            /usr/local/lib/python3.9/site-packages
        
        Perhaps your account does not have write access to this directory?  If the
        installation directory is a system-owned directory, you may need to sign in
        as the administrator or "root" account.  If you do not have administrative
        access to this machine, you may wish to choose a different installation
        directory, preferably one that is listed in your PYTHONPATH environment
        variable.
        
        For information on other options, you may wish to consult the
        documentation at:
        
          https://setuptools.pypa.io/en/latest/deprecated/easy_install.html
        
        Please make the appropriate changes for your system and try again.
        
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [31 lines of output]
    running develop
    /tmp/pip-build-env-7n8ni26y/overlay/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /tmp/pip-build-env-7n8ni26y/overlay/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/test-easy-install-11642.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/local/lib/python3.9/site-packages
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.pypa.io/en/latest/deprecated/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
*** Error code 1

Stop.
```

**Comment by yurivict** [comment]
Maybe the best solution is to add ```setup.py```?
Python projects with ```setup.py``` are very well behaved. It looks like pip isn't nearly as mature.

**Comment by jwoehr** [comment]
This error:
```
        The following error occurred while trying to add or remove files in the
        installation directory:
        
            [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/test-easy-install-11642.write-test'
        
        The installation directory you specified (via --install-dir, --prefix, or
        the distutils default setting) was:
        
            /usr/local/lib/python3.9/site-packages
```
is your mistake, not the install.
You are trying to install the system directories.
Just create a virtual environment, activate it, and install into the virtual environment.

**Comment by yurivict** [comment]
> This error [...] is your mistake, not the install.

No, ```--root {stage-dir}``` is specified for pip to install files into.
It ignores the stage directory and attempts to write into ```$prefix```.

**Comment by yurivict** [comment]
What I need is very simple: the project should be installed into a stage directory.
I definitely don't need virtual environment, because (1) I am not planning to run it from the stage directory (2) all dependencies are already installed.

I thought that this command should do it:
> cd openqasm/source/openqasm && pip install --root=${STAGEDIR} --prefix=${PREFIX} -e .

but it breaks, see above.

The ultimate purpose is to create a FreeBSD port.

OpenQASM currently has no packages, see the search on [Repology](https://repology.org/projects/?search=openqasm), because packaging is either impossible, or very non-obvious.

Does anybody know what is the correct command to install OpenQASM into a stage directory?

**Comment by yurivict** [comment]
I was able to build using the ```build``` tool.

Is OpenASM supposed to install an executable?

**Comment by jwoehr** [comment]
The OpenQASM repo includes a reference parser, but not a reference compiler.
Using the parser requires understanding the code.
There was a reference compiler written as part of a Qiskit Mentorship in Autumn of 2021.
It was written against an earlier version of the reference parser.
[That Mentorship project is here](https://github.com/mentor-fall2021-openqasm).

**Comment by yurivict** [comment]
@jwoehr 
Are there plans to merge the reference compiler into this project?

**Comment by jwoehr** [comment]
I do not believe there currently is such a plan, @yurivict

**Comment by jakelishman** [comment]
This repository is not primarily a Python package, and the Makefile in the root is purely for helping to build the live specification of the OpenQASM 3 web page.  It is not supposed to build any Python package itself.  The Python package that creates a reference AST and parser for the language is in the `source/openqasm` directory, which it looks like you found.

> I thought that this command should do it [...]

There is a [readme included in the Python package's directory](https://github.com/openqasm/openqasm/tree/main/source/openqasm#readme), which answers many of the questions in this issue about building the package.  In addition, the package does not require a `setup.py` file, because it has no dynamic components to its setup, so its entire configuration is in the `setup.cfg` file.  This is [the recommended way of packaging Python projects under PEP 517 using `setuptools`](https://setuptools.pypa.io/en/latest/build_meta.html).  Packages building with a PEP-517 compatible builder (such as `pip` or `build`) without an explicit `setup.py` are equivalent to those that have a `setup.py` file that contains only `import setuptools; setuptools.setup()`.

There's no logic in the Python package that we provide that should affect the `--root`, `--editable` or `--prefix` options to `pip` or to `setuptools`' builders.  (Really, there's no logic at all, only metadata - that's why we don't need a `setup.py` file.)  If your command isn't doing as you expect, it may be an issue with your choice of options to `pip`.  It seems odd to me that you'd specify both a `--root` _and_ `--editable`, for example.

While it's not really my business, I'm somewhat surprised you find it necessary to try and package this.  It's a pure-Python package with no compiled extensions, so it seems odd to package it at the OS level, rather than just allowing users to use `pip`.
